### ISSUE TITLE
Body Anchor doesn't work on bazzite.

### ISSUE THREAD

**Issue by Globetrotter129** [wheaney/decky-XRGaming#18]
Doesn't work on non-steam or steam games.

**Comment by wheaney** [comment]
Since it's not running in a deck you need to follow the recommendation in step 3 here: https://github.com/wheaney/breezy-desktop?tab=readme-ov-file#manual-installation

**Comment by Globetrotter129** [comment]
> Since it's not running on a deck you need to follow the recommendation in step 3 here: https://github.com/wheaney/breezy-desktop?tab=readme-ov-file#manual-installation

Thanks. Global vkbasalt brakes games from lunching but per game worked thanks.
