### ISSUE TITLE
Changing the perceived distance of the screen.

### ISSUE THREAD

**Issue by Globetrotter129** [wheaney/decky-XRGaming#20]
This isn't an issue but it would be nice to be able to change the screen distance which can be done in reshade by changing the ipd values  in the superdepth3dVR shader. I don't know if it would be possible to use your plugin as a front-end to change those values I doubt it XD.

**Comment by wheaney** [comment]
In decky, you can use the display distance slider once you've enabled side-by-side mode in the advanced settings when using the virtual display. Be sure to read through the whole dialog that pops up before using it, though.
