### ISSUE TITLE
TCL Glasses not detected

### ISSUE THREAD

**Issue by Kup86** [wheaney/decky-XRGaming#25]
Hi, 

First off, great work! You are doing what often the manufacturers neglect to do and that is implementing software that takes full advantage of the hardware. There is so much untapped potential with the XR glasses. I hope your project grows and inspires!

Now to my issue :) 

I have a pair of TCL Glasses that is usually labelled TCL NXTWEAR Air when sold. The model number is XRGT78. As the issue title goes, the glasses are not acknowledged by Decky-XR. They work as a default 'monitor glasses' with the image always following your front but as far as the app is concerned, they are not connected. Glasses are updated to latest firmware available.

In the compatibility table, it shows NXTWEAR S/S+; Air 2 as being compatible so I assumed my glasses were included in this group. I have added a pic of the glasses for reference:

![PXL_20240913_115620641 MP](https://github.com/user-attachments/assets/24660d02-dbec-4333-8c01-506b08262c3d)
![PXL_20240913_124122703 MP](https://github.com/user-attachments/assets/ae955d5f-aa9a-4f88-a31e-f7c18cc41141)

Cheers and thank you again!

**Comment by wheaney** [comment]
Hi, I haven't heard of the NXTWEAR Air, and maybe I should split RayNeo and TCL brands up into their own rows in that table because the "Aiir" listed there is specifically the RayNeo Air glasses. I know there are some older TCL glasses that aren't supported by the SDK that the RayNeo development team provided me, so it seems like probably this falls into a similar category. But if you plug in the glasses and run `lsusb` from a command line (Konsole app on Steam Deck), can you send me output? This will help me understand how the glasses are identifying themselves to the PC.

**Comment by Kup86** [comment]
Hi, Thank you for your quick reply. I have added the output below. Seems to detect it as "Bus 001 Device 010: ID 1bbb:af50 T & A Mobile Phones Smart Glasses Human interface"

When I use the TCL XR windows app for it, the glasses appear to have gyro and can have a screen fixed in one place so technically it supports those AR/XR type features.

Happy to do more testing if you feel its worthwhile. Cheers.

(deck@steamdeck ~)$ sudo lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 13d3:3553 IMC Networks Bluetooth Radio
Bus 003 Device 002: ID 28de:1205 Valve Software Steam Controller
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 010: ID 1bbb:af50 T & A Mobile Phones Smart Glasses Human interface
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by wheaney** [comment]
That is indeed using the [same HID IDs](https://github.com/wheaney/XRLinuxDriver/blob/main/src/devices/rayneo.c#L27-L28) as the rest of the TCL/RayNeo lineup, but to my understanding the SDK I was provided doesn't support some of the older models of glasses; I'm not sure if this model falls in that category. I've reached out to the RayNeo dev team and will get back to you once I hear back.

**Comment by Kup86** [comment]
Hi, 
That makes sense as the TCL software for the RayNeo is also the official software for these glasses. I figured they would have workings in common.

I look forward to hearing what the dev team comes back with. Thank you very much again for your help.

**Comment by wheaney** [comment]
Hi, this fell off my radar, but I heard back from the RayNeo team and they confirmed that the RayNeo Air isn't supported with the SDK they provided me. Sorry!
