### ISSUE TITLE
Lock mouse pointer to content?

### ISSUE THREAD

**Issue by GaryTheGravelGuy** [wheaney/decky-XRGaming#33]
It can be nearly impossible to click on stuff in nested desktop, or in any program that doesn't draw its own mouse pointer.

Is there a way to lock the mouse pointer to content instead of the display, or at least force Plasma to draw its own mouse pointer when in nested desktop?

**Comment by wheaney** [comment]
This is a duplicate of #29 (although that mentions SBS, that mode isn't really related).
