### ISSUE TITLE
Viture Pro not detected when not connected directly

### ISSUE THREAD

**Issue by sponge** [wheaney/decky-XRGaming#35]
Hi!

I appear to be unable to get the XR Gaming plugin to detect my Viture Pro glasses when plugged into either of these accessories:

https://www.viture.com/product/viture-pro-mobile-dock
https://www.viture.com/product/usb-c-xr-charging-adapter-for-usb-c-iphones

I also believe I was having the same issue when trying a generic USB hub. The XR Plugin in Decky just says no device detected. As a result, I'm unable to charge the device and use the plugin at the same time. Not sure if these things just need to have their proper USB IDs whitelisted or what, but I'm glad to provide whatever info is needed to get these working, if it is possible to!

**Comment by wheaney** [comment]
The two devices you linked are known to not pass USB data back to the PC. The Pro dock isn't intended to do this (it's just for media consumption, no 3DoF), and the charging adapter IS intended to, but the iPhone version only sends data to an iPhone. VITURE sells another version of the charging adapter that works with PCs, Steam Deck, etc...
