### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by silarsis** [wheaney/decky-XRGaming#37]
Getting "There was an error during setup." message when first running XR Gaming. Can't see anything of note in `journalctl --grep xreal` - some sudo lines rm'ing a set of /etc/udev/rules.d/70-*-xr.rules files, but that looks alright. Can't see a ~/.xreal_driver_log.

Running XR Gaming 1.0.2 on Steam 3.6.20 (build 20241030.1)

Not sure where else to get information from. I went through journalctl generally looking for anything, and can't see a clear sign of what's going wrong.

**Comment by wheaney** [comment]
Probably the same issue as https://github.com/wheaney/decky-XRGaming/issues/36
