### ISSUE TITLE
"Will this game work?" mode

### ISSUE THREAD

**Issue by wheaney** [wheaney/decky-XRGaming#6]
Add a mode to the plugin that will allow people to launch a game without glasses connected and see if the game will work with virtual display mode. Would help resolve situations [like this](https://www.reddit.com/r/Xreal/comments/17s6kbm/fuuuuck_should_i_buy_these_or_not/k8o39i7/).

Two ways to approach this:
1. Have the shader just render some kind of banner image that shows a checkmark or "works!"
2. Allow the Steam Deck's gyro (or just the mouse, which may actually achieve the gyro solution as well) to move the screen.

**Comment by Maz111111** [comment]
It would also be a great help for troubleshooting.

By now I am trying to examin, why on my deck moonlight is not recognized by your plug in, while on other peoples deck with the same setup (PREFER_VULKAN=1 %command%) it is working.

When your plugin would show, if it detects a "vulkan stream" like it shows to which glasses it is connected, it could be helpful.

At the moment I can't even tell whether the plugin is registering a video stream based on Vulkan but is simply not being triggered - which could indicate a bug in the plugin under certain environments - or whether the plugin on my deck for some reason doesn't even recognize a usable video stream when I start moonlight.

**Comment by wheaney** [comment]
This is no longer needed since Vulkan-only mode is no longer used by most people.
